Repository ProjectMIKO/miko-main-server, pull requests merged in 2024-07, with the labels that each got.

#48 result page 처리를 메인페이지에 병합
  src/app/gateway/app.gateway.ts
  src/assets/global/filter/global.exceptions.filter.ts
  src/components/conversation/controller/conversation.controller.ts
  src/components/conversation/dto/conversation.update.dto.ts
  src/components/conversation/service/conversation.service.ts
  src/components/edge/controller/edge.controller.ts
  src/components/meeting/controller/meeting.controller.ts
  src/components/meeting/dto/meeting.create.dto.ts
  src/components/meeting/dto/meeting.find.response.dto.ts
  src/components/meeting/meeting.module.ts
  src/components/meeting/schema/meeting.schema.ts
  src/extern/openvidu/controller/openvidu.controller.ts
  src/extern/openvidu/dto/recording.response.dto.ts
  src/extern/openvidu/openvidu.module.ts
  src/extern/openvidu/service/openvidu.service.ts
Labels: enhancement

#54 비밀번호 및 방 생성 API 구현
  src/app/app.module.ts
  src/app/controller/app.controller.spec.ts
  src/app/controller/app.controller.ts
  src/app/dto/room.create.dto.ts
  src/app/gateway/app.gateway.spec.ts
  src/app/gateway/app.gateway.ts
  src/app/service/app.service.spec.ts
  src/app/service/app.service.ts
  src/assets/global/exception/emptyData.exception.ts
  src/assets/global/exception/invalidPassword.exception.ts
  src/assets/global/filter/global.exceptions.filter.ts
  src/assets/global/warning/emptyData.warning.ts
  src/components/meeting/dto/meeting.create.dto.ts
  src/components/meeting/dto/meeting.update.dto.ts
  src/components/meeting/service/meeting.service.ts
Labels: enhancement

#55 버그 수정한 것 main으로 pull
  src/app/controller/app.controller.ts
  src/app/dto/room.create.dto.ts
  src/app/gateway/app.gateway.ts
  src/app/service/app.service.ts
  src/assets/global/exception/roomNotFound.exception.ts
  src/assets/global/filter/global.exceptions.filter.ts
Labels: bug

#64 blob 그대로 stt 요청을 메인 브랜치에 병합
  src/app/gateway/app.gateway.ts
  src/middleware/service/middleware.service.ts
Labels: enhancement

#66 failed여도 결과페이지에 recording 파일 반환을 메인 브랜치에 병합
  src/components/meeting/controller/meeting.controller.ts
Labels: bug

#71 Dev/owner
  src/app/gateway/app.gateway.ts
  src/components/meeting/controller/meeting.controller.ts
  src/components/meeting/dto/meeting.list.response.dto.ts
  src/components/meeting/schema/meeting.schema.ts
  src/components/meeting/service/meeting.service.ts
Labels: enhancement, invalid

#74 meeting 회의록 미들웨어 api 버그 수정을 메인 브랜치에 병합
  src/components/meeting/controller/meeting.controller.ts
  src/components/meeting/dto/meeting.find.response.dto.ts
  src/middleware/dto/mom.response.dto.ts
  src/middleware/service/middleware.service.ts
Labels: bug

#76 결과페이지 회의록 participants 추가를 메인 브랜치에 병합
  src/components/meeting/controller/meeting.controller.ts
  src/components/meeting/dto/meeting.find.response.dto.ts
  src/middleware/dto/mom.response.dto.ts
Labels: enhancement

#80 회의록을 SSE로 미리 나간 참여자들한테 제공을 메인 브랜치에 병합
  src/app/gateway/app.gateway.ts
  src/components/meeting/controller/meeting.controller.ts
Labels: enhancement

#82 녹화 완료되면 음성파일 보내도록 수정을 메인 브랜치에 병합
  src/app/gateway/app.gateway.ts
  src/components/meeting/controller/meeting.controller.ts
  src/components/meeting/schema/meeting.schema.ts
Labels: enhancement

#84 summarize 메서드 리팩토링을 메인 브랜치에 병합
  package-lock.json
  package.json
  src/app/gateway/app.gateway.ts
  src/middleware/dto/summarize.response.dto.ts
Labels: enhancement

#86 중간 참여시 batch size(10개) 별로 전송을 병합
  src/app/gateway/app.gateway.ts
  src/components/meeting/service/meeting.service.ts
Labels: enhancement

#88 mom schema 삭제 및 mom 안정화을 메인 브랜치에 병합
  src/app/gateway/app.gateway.ts
  src/components/meeting/controller/meeting.controller.ts
  src/components/meeting/dto/meeting.find.response.dto.ts
  src/components/meeting/meeting.module.ts
  src/components/meeting/schema/meeting.schema.ts
  src/components/meeting/schema/mom.schema.ts
  src/components/meeting/service/meeting.service.ts
  src/middleware/dto/mom.response.dto.ts
  src/middleware/service/middleware.service.ts
Labels: enhancement

#96 결과창 예외처리 메인 브랜치에 병합
  src/app/gateway/app.gateway.ts
  src/components/meeting/controller/meeting.controller.ts
  src/extern/openvidu/dto/recording.response.dto.ts
  src/extern/openvidu/service/record.service.ts
Labels: bug

#98 한글 이름으로 방 생성 가능
  src/app/gateway/app.gateway.ts
  src/app/service/app.service.ts
  src/extern/openvidu/dto/session.request.dto.ts
  src/extern/openvidu/service/openvidu.service.ts
Labels: enhancement

#102 429 에러 처리를 메인 브랜치에 병합
  src/app/gateway/app.gateway.ts
  src/middleware/dto/convert.response.dto.ts
  src/middleware/service/middleware.service.ts
Labels: bug

#103 SummarizeResponseDto 변경 사항 원복을 메인 브랜치에 병합
  src/app/gateway/app.gateway.ts
  src/middleware/dto/summarize.response.dto.ts
Labels: bug
